version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
      - image: circleci/mysql:8.0.21
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: unittest_pwd
          MYSQL_HOST: '%'
          MYSQL_DATABASE: ethereum_events_unittest_db
          MYSQL_USER: unittest_root
          MYSQL_PASSWORD: unittest_pwd
    working_directory: ~/singnet
    steps:
      - checkout
      - run:
          name: Generating checksum for all requirements file
          command: |
            shasum */requirement*.txt > /tmp/checksum_files_list
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown circleci:circleci -R /usr/local/lib/python3.7
      - run:
          name: Revert the permissions
          command: |
            sudo chown root:root -R /usr/local/bin
            sudo chown root:root -R /usr/local/lib/python3.7
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install dependencies
          command: |
            sudo pip install -r .circleci/requirements.txt --prefer-binary
            npm install
      - run:
          name: Install required packages.
          command: |
            sudo apt update --allow-releaseinfo-change
            sudo apt install unzip -y
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            sudo apt install default-mysql-client
            sudo pip install coverage coveralls pytest alembic
            mysql -h 127.0.0.1 -u root -punittest_pwd -e "GRANT ALL PRIVILEGES ON *.* TO 'unittest_root'@'%';"
            export PYTHONPATH=$PWD
            alembic upgrade head
            mysql -h 127.0.0.1 -u unittest_root -punittest_pwd ethereum_events_unittest_db < script/db/script.sql
      - run:
          name: Run unit tests and integration test
          command: |
            PYTHONPATH=$PWD python -m coverage run -m pytest testcases/functional_testcases/*.py
            python -m coverage report -m
            coverage xml -i
            sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarqube.singularitynet.io -Dsonar.login=${SONAR_TOKEN} $SONAR_SCANNER_OPTS_CUSTOM
      - save_cache:
          key: dependency-cache-{{ checksum "/tmp/checksum_files_list" }}
          paths:
            - /usr/local/lib/python3.7/site-packages